# Generated by Django 5.2.14 on 2026-05-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleTermino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.IntegerField(verbose_name='Etapa do Término (1 ou 2)')),
                ('acao', models.CharField(choices=[('prorrogado', 'Prorrogado'), ('termino', 'Término'), ('manter', 'Manter')], max_length=20, verbose_name='Ação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('respondido_por', models.CharField(blank=True, max_length=255, verbose_name='Respondido Por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_termino', to='colaboradores.colaborador')),
            ],
            options={
                'verbose_name': 'Controle de Término',
                'verbose_name_plural': 'Controles de Término',
                'ordering': ['-created_at'],
            },
        ),
    ]
