# Generated by Django 5.2.14 on 2026-05-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_colaborador_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='funcao_gestao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Função (Gestão)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='loja_gestao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Loja (Gestão)'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='status_gestao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Status (Gestão)'),
        ),
    ]
