# Generated by Django 5.2.14 on 2026-05-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_colaborador_atestados_geovictoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='atestados_geovictoria',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='faltas_geovictoria',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='geovictoria_atualizado_em',
        ),
    ]
