# Generated by Django 5.2.14 on 2026-06-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0010_colaborador_geovictoria_resumo'),
        ('lojas', '0026_supervisor_coordenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_manual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Loja Manual')),
                ('funcao', models.CharField(default='Apoio', max_length=150, verbose_name='Função a Exercer')),
                ('data', models.DateField(verbose_name='Data do Roteiro')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('concluido', 'Concluído'), ('folga', 'Folga'), ('livre', 'Sem Loja (Livre)'), ('faltou', 'Falta')], default='agendado', max_length=20, verbose_name='Status')),
                ('turno', models.CharField(default='noturno', max_length=20, verbose_name='Turno')),
                ('hora_entrada', models.CharField(blank=True, max_length=10, null=True, verbose_name='Hora Entrada')),
                ('hora_saida', models.CharField(blank=True, max_length=10, null=True, verbose_name='Hora Saída')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='colaboradores.colaborador', verbose_name='Colaborador')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data'],
                'unique_together': {('colaborador', 'data')},
            },
        ),
    ]
