# Generated by Django 5.2.14 on 2026-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0011_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('concluido', 'Concluído'), ('folga', 'Folga'), ('livre', 'Sem Loja (Livre)'), ('faltou', 'Falta'), ('atestado', 'Atestado')], default='agendado', max_length=20, verbose_name='Status'),
        ),
    ]
