# Generated by Django 5.2.14 on 2026-06-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0012_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status_gestao',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Status (Gestão)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='termino_1',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Término 1'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='termino_2',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Término 2'),
        ),
    ]
