# Generated by Django 5.2.14 on 2026-07-07 14:34

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0013_alter_colaborador_cargo_alter_colaborador_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestePromocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('ativo', 'Ativo'), ('promovido', 'Promovido'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('anexo', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\guilherme.satoru\\Desktop\\testes'), upload_to='', verbose_name='Anexo da Folha de Teste')),
                ('criado_por', models.CharField(blank=True, max_length=255, verbose_name='Criado Por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testes_promocao', to='colaboradores.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Teste de Promoção',
                'verbose_name_plural': 'Testes de Promoção',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAcaoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('ativar', 'Aprovar/Ativar'), ('pagar_premio', 'Pagar Prêmio'), ('promover', 'Promover'), ('cancelar', 'Cancelar')], max_length=20, verbose_name='Ação')),
                ('mes_referencia', models.IntegerField(verbose_name='Mês de Referência')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('solicitado_por', models.CharField(blank=True, max_length=255, verbose_name='Solicitado Por')),
                ('realizado_por', models.CharField(blank=True, max_length=255, verbose_name='Realizado Por')),
                ('data_acao', models.DateField(verbose_name='Data da Ação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_acoes', to='colaboradores.testepromocao', verbose_name='Teste de Promoção')),
            ],
            options={
                'verbose_name': 'Histórico de Ação do Teste',
                'verbose_name_plural': 'Históricos de Ações dos Testes',
                'ordering': ['created_at'],
            },
        ),
    ]
