# Generated by Django 5.2.14 on 2026-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0014_testepromocao_historicoacaoteste'),
    ]

    operations = [
        migrations.AddField(
            model_name='testepromocao',
            name='cargo_teste',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo em Teste'),
        ),
    ]
