# Generated by Django 5.2.14 on 2026-07-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0015_testepromocao_cargo_teste'),
        ('lojas', '0031_loja_headcount_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaRelogio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID da Batida')),
                ('cpf_original', models.CharField(db_index=True, max_length=15, verbose_name='CPF da Batida')),
                ('grupo_geovictoria', models.CharField(max_length=255, verbose_name='Grupo Original GeoVictoria')),
                ('data', models.DateField(db_index=True, verbose_name='Data da Batida')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora da Entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias_relogio', to='colaboradores.colaborador', verbose_name='Colaborador Resolvido')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencias_relogio', to='lojas.loja', verbose_name='Loja Resolvida')),
            ],
            options={
                'verbose_name': 'Presença do Relógio',
                'verbose_name_plural': 'Presenças do Relógio',
                'ordering': ['-data_hora'],
            },
        ),
    ]
