# Generated by Django 5.2.14 on 2026-07-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0016_presencarelogio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoacaoteste',
            name='resposta_supervisor',
            field=models.CharField(blank=True, choices=[('pagar_premio', 'Pagar Prêmio'), ('promover', 'Promover'), ('cancelar', 'Cancelar')], max_length=20, null=True, verbose_name='Resposta do Supervisor'),
        ),
        migrations.AlterField(
            model_name='historicoacaoteste',
            name='acao',
            field=models.CharField(choices=[('ativar', 'Aprovar/Ativar'), ('registrar_resposta', 'Registrar Resposta do Supervisor'), ('pagar_premio', 'Pagar Prêmio'), ('promover', 'Promover'), ('cancelar', 'Cancelar')], max_length=20, verbose_name='Ação'),
        ),
    ]
