# Generated by Django 5.2.14 on 2026-07-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0017_historicoacaoteste_resposta_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='motivo_demissao',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Motivo de Demissão'),
        ),
    ]
