# Generated by Django 5.2.14 on 2026-07-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0018_colaborador_motivo_demissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoacaoteste',
            name='acao',
            field=models.CharField(choices=[('ativar', 'Aprovar/Ativar'), ('registrar_resposta', 'Registrar Resposta do Supervisor'), ('pagar_premio', 'Pagar Prêmio'), ('promover', 'Promover'), ('cancelar', 'Cancelar'), ('pagar_premio_cancelar', 'Pagar Prêmio e Cancelar')], max_length=30, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='historicoacaoteste',
            name='resposta_supervisor',
            field=models.CharField(blank=True, choices=[('pagar_premio', 'Pagar Prêmio'), ('promover', 'Promover'), ('cancelar', 'Cancelar'), ('pagar_premio_cancelar', 'Pagar Prêmio e Cancelar')], max_length=30, null=True, verbose_name='Resposta do Supervisor'),
        ),
    ]
