# Generated by Django 5.2.14 on 2026-07-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0019_alter_historicoacaoteste_acao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('falta', 'Falta'), ('atestado', 'Atestado'), ('suspensao', 'Suspensão')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição Original')),
                ('data', models.DateField(db_index=True, verbose_name='Data da Ausência')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias_registradas', to='colaboradores.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Ausência',
                'verbose_name_plural': 'Ausências',
                'ordering': ['-data'],
                'unique_together': {('colaborador', 'data')},
            },
        ),
    ]
