# Generated by Django 5.2.14 on 2026-07-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0020_ausencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='atestados_geovictoria',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='faltas_geovictoria',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='geovictoria_atualizado_em',
        ),
    ]
