# Generated by Django 5.2.14 on 2026-07-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0021_remove_colaborador_atestados_geovictoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausencia',
            name='observacao',
        ),
    ]
