# Generated by Django 5.2.14 on 2026-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_referencia', models.CharField(max_length=120, unique=True, verbose_name='Nome Referência')),
                ('centro_de_custo', models.CharField(max_length=50, verbose_name='Centro de Custo')),
                ('quadro', models.CharField(max_length=80, verbose_name='Quadro')),
                ('nome_geovictoria', models.CharField(blank=True, max_length=120, verbose_name='Nome GeoVictoria')),
                ('nome_gestao', models.CharField(blank=True, max_length=120, verbose_name='Nome Gestão')),
                ('nome_totvs', models.CharField(blank=True, max_length=120, verbose_name='Nome TOTVS')),
                ('nome_financeiro', models.CharField(blank=True, max_length=120, verbose_name='Nome Financeiro')),
                ('nome_findme', models.CharField(blank=True, max_length=120, verbose_name='Nome FindMe')),
                ('nome_matriz', models.CharField(blank=True, max_length=120, verbose_name='Nome Matriz')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('cliente', models.CharField(blank=True, max_length=120, verbose_name='Cliente')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('EM_IMPLANTACAO', 'Em Implantação'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=20, verbose_name='Status')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, max_length=200, verbose_name='Rua')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, max_length=120, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('sub_regiao', models.CharField(blank=True, max_length=80, verbose_name='Sub-Região')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['nome_referencia'],
            },
        ),
    ]
