# Generated by Django 5.2.14 on 2026-05-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_alter_loja_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='nome_matriz',
        ),
        migrations.AddField(
            model_name='loja',
            name='codigo_loja',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cód. Loja'),
        ),
        migrations.AddField(
            model_name='loja',
            name='nome_metricas',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome Métricas'),
        ),
    ]
