# Generated by Django 5.2.14 on 2026-05-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_remove_loja_nome_matriz_loja_codigo_loja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EscopoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data início')),
                ('data_fim', models.DateField(blank=True, help_text='Vazio = escopo ainda aberto.', null=True, verbose_name='Data fim')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escopos', to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Escopo da loja',
                'verbose_name_plural': 'Escopos das lojas',
                'ordering': ['-data_inicio', 'loja'],
            },
        ),
        migrations.CreateModel(
            name='ItemEscopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('DIURNO', 'Diurno'), ('NOTURNO', 'Noturno')], max_length=10, verbose_name='Turno')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_escopo', to='lojas.cargo', verbose_name='Cargo')),
                ('escopo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='lojas.escopoloja', verbose_name='Escopo')),
            ],
            options={
                'verbose_name': 'Item do escopo',
                'verbose_name_plural': 'Itens do escopo',
                'ordering': ['escopo', 'cargo', 'turno'],
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor base')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salarios', to='lojas.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Salário',
                'verbose_name_plural': 'Salários',
                'ordering': ['-ano', 'uf', 'cargo'],
                'constraints': [models.UniqueConstraint(fields=('cargo', 'uf', 'ano'), name='unique_lojas_salario_cargo_uf_ano')],
            },
        ),
    ]
