# Generated by Django 5.2.14 on 2026-05-07 15:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0005_alter_loja_uf_alter_salario_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='escopoloja',
            name='insalubridade_banheirista_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual aplicado sobre o salário mínimo nacional (UF=BR).', max_digits=5, verbose_name='Insalubridade banheirista (%)'),
        ),
        migrations.AddField(
            model_name='escopoloja',
            name='insalubridade_fixa_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual aplicado sobre o salário base regional (ex.: 20.00).', max_digits=5, verbose_name='Insalubridade fixa (%)'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='uf',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('BR', 'BR')], max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='uf',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('BR', 'BR')], max_length=2, verbose_name='UF'),
        ),
    ]
