# Generated by Django 5.2.14 on 2026-05-08 17:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0006_escopoloja_insalubridade_banheirista_percentual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscopoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('insalubridade_fixa_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Insalubridade fixa (%)')),
                ('insalubridade_banheirista_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Insalubridade banheirista (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escopos_mensais', to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Escopo mensal',
                'verbose_name_plural': 'Escopos mensais',
                'ordering': ['-ano', '-mes', 'loja'],
            },
        ),
        migrations.CreateModel(
            name='ItemEscopoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('DIURNO', 'Diurno'), ('NOTURNO', 'Noturno')], max_length=10, verbose_name='Turno')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_escopo_mensal', to='lojas.cargo', verbose_name='Cargo')),
                ('escopo_mensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='lojas.escopomensal', verbose_name='Escopo mensal')),
            ],
            options={
                'verbose_name': 'Item do escopo mensal',
                'verbose_name_plural': 'Itens do escopo mensal',
                'ordering': ['escopo_mensal', 'cargo', 'turno'],
            },
        ),
        migrations.AddConstraint(
            model_name='escopomensal',
            constraint=models.UniqueConstraint(fields=('loja', 'ano', 'mes'), name='unique_escopo_mensal_loja_ano_mes'),
        ),
        migrations.AddConstraint(
            model_name='itemescopomensal',
            constraint=models.UniqueConstraint(fields=('escopo_mensal', 'cargo', 'turno'), name='unique_item_escopo_mensal'),
        ),
    ]
