# Generated by Django 5.2.14 on 2026-05-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0007_escopomensal_itemescopomensal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemescopo',
            name='escopo',
        ),
        migrations.RemoveField(
            model_name='itemescopo',
            name='cargo',
        ),
        migrations.DeleteModel(
            name='EscopoLoja',
        ),
        migrations.DeleteModel(
            name='ItemEscopo',
        ),
    ]
