# Generated by Django 5.2.14 on 2026-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0009_escopo_insalubridade_padroes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verba', models.CharField(max_length=20, unique=True, verbose_name='Código da verba')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo_codigo', models.CharField(choices=[('PROVENTO', 'Provento'), ('BASE DESCONTO', 'Base Desconto'), ('BASE PROVENTO', 'Base Provento'), ('DESCONTO', 'Desconto')], max_length=20, verbose_name='Tipo do código')),
                ('categoria', models.CharField(blank=True, max_length=120, verbose_name='Categoria')),
                ('considerar_na_contagem', models.BooleanField(default=False, verbose_name='Considerar na contagem')),
            ],
            options={
                'verbose_name': 'Verba',
                'verbose_name_plural': 'Verbas',
                'ordering': ['codigo_verba'],
            },
        ),
    ]
