# Generated by Django 5.2.14 on 2026-05-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0011_linha_folha'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaFolhaDuplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('REPETIDA_NO_ARQUIVO', 'Repetida no mesmo arquivo'), ('JA_EXISTIA_NO_BANCO', 'Já existia na folha gravada')], max_length=32, verbose_name='Motivo')),
                ('matricula', models.CharField(max_length=64, verbose_name='Matrícula')),
                ('codigo_verba', models.CharField(max_length=20, verbose_name='Código da verba (cópia)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('dt_arq', models.DateField(verbose_name='Data ARQ (competência)')),
                ('dt_pagamento', models.DateField(verbose_name='Data pagamento')),
                ('centro_custo', models.CharField(max_length=12, verbose_name='Centro de custo (folha)')),
                ('centro_custo_real', models.CharField(max_length=12, verbose_name='Centro de custo real')),
                ('categoria', models.CharField(blank=True, max_length=120, verbose_name='Categoria')),
                ('arquivo_origem', models.CharField(blank=True, max_length=255, verbose_name='Arquivo de origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Linha de folha duplicada',
                'verbose_name_plural': 'Linhas de folha duplicadas (histórico)',
                'ordering': ['-created_at', 'matricula'],
            },
        ),
        migrations.RenameIndex(
            model_name='linhafolha',
            new_name='lojas_linha_dt_arq_927c4a_idx',
            old_name='lojas_linha_dt_arq_6e8b8f_idx',
        ),
        migrations.RenameIndex(
            model_name='linhafolha',
            new_name='lojas_linha_matricu_b62715_idx',
            old_name='lojas_linha_matricu_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='linhafolha',
            new_name='lojas_linha_codigo__c4de94_idx',
            old_name='lojas_linha_codigo_3d4e5f_idx',
        ),
        migrations.AddField(
            model_name='linhafolhaduplicada',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_folha_duplicadas', to='lojas.loja', verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='linhafolhaduplicada',
            name='verba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_folha_duplicadas', to='lojas.verba', verbose_name='Verba'),
        ),
        migrations.AddIndex(
            model_name='linhafolhaduplicada',
            index=models.Index(fields=['dt_arq', 'motivo'], name='lojas_linha_dt_arq_98af9a_idx'),
        ),
        migrations.AddIndex(
            model_name='linhafolhaduplicada',
            index=models.Index(fields=['matricula', 'dt_arq'], name='lojas_linha_matricu_a395d5_idx'),
        ),
    ]
