# Generated by Django 5.2.14 on 2026-05-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0016_insalubridade_fixa_recebedores_na_config_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=20, unique=True, verbose_name='RE')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('centro_custo', models.CharField(max_length=50, verbose_name='Centro de Custo')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('termino_1', models.DateField(blank=True, null=True, verbose_name='Término 1')),
                ('termino_2', models.DateField(blank=True, null=True, verbose_name='Término 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
    ]
