# Generated by Django 5.2.14 on 2026-05-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0017_colaborador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
