# Generated by Django 5.2.14 on 2026-05-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0018_delete_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='coordenador',
            field=models.CharField(blank=True, max_length=120, verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='loja',
            name='supervisor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Supervisor'),
        ),
    ]
