# Generated by Django 5.2.14 on 2026-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0019_loja_coordenador_loja_supervisor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['nome'], name='lojas_cargo_nome_ac83b8_idx'),
        ),
        migrations.AddIndex(
            model_name='linhafolha',
            index=models.Index(fields=['matricula', 'valor', 'dt_arq', 'verba'], name='lojas_linha_matricu_b5e257_idx'),
        ),
    ]
