# Generated by Django 5.2.14 on 2026-06-09 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0022_coordenador_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id_diaria', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID da Diária')),
                ('diarista', models.CharField(max_length=255, verbose_name='Nome do Diarista')),
                ('local', models.CharField(max_length=255, verbose_name='Local (texto original)')),
                ('data_servico', models.DateField(verbose_name='Data do Serviço')),
                ('turno', models.CharField(max_length=100, verbose_name='Turno')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('solicitante', models.CharField(max_length=255, verbose_name='Solicitante')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Diária')),
                ('status', models.CharField(max_length=100, verbose_name='Status do Pagamento')),
                ('ultima_atualizacao', models.DateField(verbose_name='Última Atualização')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarias', to='lojas.loja', verbose_name='Loja Associada (TOTVS)')),
            ],
            options={
                'verbose_name': 'Diária',
                'verbose_name_plural': 'Diárias',
                'ordering': ['-data_servico', 'id_diaria'],
            },
        ),
    ]
