# Generated by Django 5.2.14 on 2026-06-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0023_diaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Status do Prêmio')),
                ('cost_center_name', models.CharField(max_length=255, verbose_name='Centro de Custo (Original)')),
                ('verb_name', models.CharField(max_length=255, verbose_name='Tipo de Prêmio')),
                ('reward_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor do Prêmio')),
                ('period', models.CharField(max_length=20, verbose_name='Período (YYYYMM)')),
                ('order_type', models.CharField(max_length=50, verbose_name='Tipo de Pedido')),
                ('roteiro', models.CharField(max_length=50, verbose_name='Roteiro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios', to='lojas.loja', verbose_name='Loja Associada (TOTVS)')),
            ],
            options={
                'verbose_name': 'Prêmio',
                'verbose_name_plural': 'Prêmios',
                'ordering': ['-period', 'id'],
            },
        ),
    ]
