# Generated by Django 5.2.14 on 2026-06-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0024_premio'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='re',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RE'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='regiao',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Região (UF)'),
        ),
        migrations.AddField(
            model_name='premio',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios', to='lojas.coordenador', verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='premio',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios', to='lojas.supervisor', verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='premio',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('BR', 'BR')], max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='re',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RE'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='regiao',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Região (UF)'),
        ),
    ]
