# Generated by Django 5.2.14 on 2026-06-15 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0025_coordenador_re_coordenador_regiao_premio_coordenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisores', to='lojas.coordenador', verbose_name='Coordenador'),
        ),
    ]
