# Generated by Django 5.2.14 on 2026-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0026_supervisor_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='orcamento_diarias',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Orçamento Diárias'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='orcamento_premios',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Orçamento Prêmios'),
        ),
    ]
