# Generated by Django 5.2.14 on 2026-07-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0027_coordenador_orcamento_diarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='order_type',
            field=models.CharField(default='SISTEMA', max_length=50, verbose_name='Tipo de Pedido'),
        ),
    ]
