# Generated by Django 5.2.14 on 2026-07-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0028_diaria_order_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinhaFolhaDuplicada',
        ),
    ]
