# Generated by Django 5.2.14 on 2026-07-03 19:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def popular_resumos_retroativos(apps, schema_editor):
    from decimal import Decimal
    from django.db.models import Sum, Count, Case, When, Value, DecimalField, Q
    
    LinhaFolha = apps.get_model('lojas', 'LinhaFolha')
    ResumoFolhaMensal = apps.get_model('lojas', 'ResumoFolhaMensal')
    
    # Categorias da planilha de verbas
    CAT_FOLHA_SALARIO = ("SALÁRIO",)
    CAT_FOLHA_INSALUBRIDADE = ("INSALUBRIDADE",)
    CAT_FOLHA_ADICIONAL_NOTURNO = ("ADICIONAL NOTURNO",)
    
    def _q_categoria_um_dos(rotulos):
        q = Q()
        for r in rotulos:
            t = (r or "").strip()
            if t:
                q |= Q(categoria__iexact=t)
        return q
        
    q_salario = _q_categoria_um_dos(CAT_FOLHA_SALARIO)
    q_insalubridade = _q_categoria_um_dos(CAT_FOLHA_INSALUBRIDADE)
    q_adicional_noturno = _q_categoria_um_dos(CAT_FOLHA_ADICIONAL_NOTURNO)
    
    folha_qs = LinhaFolha.objects.filter(
        verba__tipo_codigo="PROVENTO",
        verba__considerar_na_contagem=True,
        loja__isnull=False
    )
    
    agregados = (
        folha_qs.values("loja_id", "dt_arq")
        .annotate(
            valor_total=Sum("valor"),
            linhas_count=Count("id"),
            valor_salario=Sum(
                Case(
                    When(q_salario, then="valor"),
                    default=Value(Decimal("0.00")),
                    output_field=DecimalField(max_digits=14, decimal_places=2),
                )
            ),
            valor_insalubridade=Sum(
                Case(
                    When(q_insalubridade, then="valor"),
                    default=Value(Decimal("0.00")),
                    output_field=DecimalField(max_digits=14, decimal_places=2),
                )
            ),
            valor_adicional_noturno=Sum(
                Case(
                    When(q_adicional_noturno, then="valor"),
                    default=Value(Decimal("0.00")),
                    output_field=DecimalField(max_digits=14, decimal_places=2),
                )
            ),
        )
    )
    
    resumos_para_criar = []
    for agg in agregados:
        resumos_para_criar.append(
            ResumoFolhaMensal(
                loja_id=agg["loja_id"],
                dt_arq=agg["dt_arq"],
                valor_total=agg["valor_total"] or Decimal("0.00"),
                linhas_count=agg["linhas_count"] or 0,
                valor_salario=agg["valor_salario"] or Decimal("0.00"),
                valor_insalubridade=agg["valor_insalubridade"] or Decimal("0.00"),
                valor_adicional_noturno=agg["valor_adicional_noturno"] or Decimal("0.00"),
            )
        )
        
    if resumos_para_criar:
        ResumoFolhaMensal.objects.bulk_create(resumos_para_criar, batch_size=2000)


def despopular_resumos_retroativos(apps, schema_editor):
    ResumoFolhaMensal = apps.get_model('lojas', 'ResumoFolhaMensal')
    ResumoFolhaMensal.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0029_delete_linhafolhaduplicada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoFolhaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_arq', models.DateField(verbose_name='Data ARQ (competência)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor total')),
                ('linhas_count', models.IntegerField(default=0, verbose_name='Contagem de linhas')),
                ('valor_salario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor salário')),
                ('valor_insalubridade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor insalubridade')),
                ('valor_adicional_noturno', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor adicional noturno')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumos_folha', to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Resumo de folha mensal',
                'verbose_name_plural': 'Resumos de folha mensal',
                'indexes': [models.Index(fields=['dt_arq', 'loja_id'], name='lojas_resum_dt_arq_6cc869_idx'), models.Index(fields=['loja_id'], name='lojas_resum_loja_id_aa97c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('loja', 'dt_arq'), name='unique_resumo_folha_loja_dt_arq')],
            },
        ),
        migrations.RunPython(
            popular_resumos_retroativos,
            despopular_resumos_retroativos
        ),
    ]

