# Generated by Django 5.2.14 on 2026-07-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0030_resumofolhamensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='headcount_real',
            field=models.IntegerField(default=0, verbose_name='Headcount Real (Gestão)'),
        ),
    ]
