# Generated by Django 5.2.14 on 2026-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0031_loja_headcount_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='loja',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
